<?php

use Joomla\CMS\Form\FormRule;

class JFormRuleOtherRule extends FormRule
{
	public function test(\SimpleXMLElement $element, $value, $group = null, \Joomla\Registry\Registry $input = null, \Joomla\CMS\Form\Form $form = null)
	{
		return strpos($value, 'b') !== false; // TODO: Change the autogenerated stub
	}
}
